// generated by dalgen -type User; DO NOT EDIT

package model

import "github.com/jmoiron/sqlx"
import _ "github.com/lib/pq"

func FindUserById(db *sqlx.DB, ID int64) (*User, error) {
	u := &User{}
	err := db.Get(u, "select * from users where id=$1", ID)
	return u, err
}

func CreateUserTable(db *sqlx.DB) error {
	sql := `create table users (
	id bigserial primary key,
	)`
	_, err := db.Exec(sql)
	return err
}
