// generated by dalgen -type User; DO NOT EDIT

package model

import "github.com/jmoiron/sqlx"
import _ "github.com/lib/pq"

func CreateUserTable(db *sqlx.DB) error {
	sql := `create table users (
		id INT NOT NULL,
		name TEXT NOT NULL)`
	_, err := db.Exec(sql)
	return err
}

func FindUserByID(db *sqlx.DB, id int64) (*User, error) {
	x := &User{}
	err := db.Get(x, "select * from users where ID =$1", id)
	return x, err
}

func FindUserByName(db *sqlx.DB, name string) (*User, error) {
	x := &User{}
	err := db.Get(x, "select * from users where Name =$1", name)
	return x, err
}
